# insert a new blank line between prompts
add_newline = true
command_timeout = 360

# Advanced prompt format
format = """\
[ ╭─────╴ ](white)$env_var\
$all[ ╰─╴](white)$character"""
#format = """$os$username$hostname$kubernetes$directory$git_branch$git_status"""

# simplified prompt characters
[character]
success_symbol = "[≫](white)"
error_symbol = "[≫ ﱥ ](red)"

# shows an icon that should be included by zshrc script based on the distro or os
[env_var.STARSHIP_DISTRO]
format = '[$env_value](bold white)'
variable = "STARSHIP_DISTRO"
disabled = false

# Shows username
[username]
style_user = "green"
style_root = "bold white"
format = "[$user]($style) "
disabled = false
show_always = true

# Shows hostname of the system or IP address
#[hostname]
#ssh_symbol = "  "
#format = """\
#[$ssh_symbol]\

#"""
#ssh_only = true
#disabled = false

# Current directory styling 
[directory]
truncation_length = 3
truncation_symbol = ".../"
home_symbol = " ~"
read_only = "  " 



# Symbol EDITOR format
[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = "  "

[crystal]
symbol = "  "

[dart]
symbol = "  "

[docker_context]
symbol = "   "

[elixir]
symbol = "  "

[elm]
symbol = "   "

[fennel]
symbol = "   "

[git_branch]
symbol = "   "
format = "via [$symbol$branch]($style)"
truncation_symbol = ".../"
style = " bold red"

[git_commit]
tag_symbol = '   '

[golang]
symbol = "  "

[guix_shell]
symbol = " "

[haskell]
symbol = "   "

[haxe]
symbol = "   "

[hg_branch]
symbol = "   "

[hostname]
ssh_symbol = "   "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "
